CREATE TABLE farm.fields (
    id integer NOT NULL,
    geom public.geometry(Polygon,4326),
    farmid integer NOT NULL,
    tstart timestamp without time zone,
    tend timestamp without time zone,
    fieldblock text,
    fieldpart text,
    fieldnumber text,
    fieldname text,
    area double precision,
    uoid integer,
    cropkey integer,
    applicationarea double precision,
    status text,
    fieldcomplex integer DEFAULT 0,
    field_user_number text,
    extent text,
    branch_of_activity_id bigint,
    info character varying(255),
    frucht_info character varying(255),
    year integer,
    totalarea double precision
) distribute by HASH(id);

CREATE TABLE nutrients.samples (
    id integer NOT NULL,
    geom public.geometry,
    samplefieldid integer,
    sampledate timestamp without time zone,
    gpsnumber numeric(10,0),
    ph double precision,
    n double precision,
    p double precision,
    k double precision,
    mg double precision,
    region text,
    landuse integer,
    soilgroup integer,
    method_p text,
    method_k text,
    method_mg text,
    class_ph text,
    class_p text,
    class_k text,
    class_mg text,
    form_p text,
    form_k text,
    form_mg text,
   method_ph text,
    fname_p text,
    fname_k text,
    fname_mg text,
    fname_ph text,
    need_p double precision DEFAULT 0,
    need_k double precision DEFAULT 0,
    need_mg double precision DEFAULT 0,
    need_ph double precision DEFAULT 0,
    fileid bigint,
    farmid integer,
    planningperiodid integer,
    real_sampledate timestamp without time zone
) distribute by HASH(fileid);

CREATE TABLE n.nsensorlogs (
    id integer NOT NULL,
    geom public.geometry,
    fileid bigint,
    date timestamp without time zone,
    altitude integer,
    marker1 smallint,
    marker2 smallint,
    marker3 smallint,
    s1 double precision,
    s2 double precision,
    sn double precision,
    applraten integer,
    applfactor smallint,
    opmode integer,
    sprraten integer,
    s1l double precision,
    s2l double precision,
    s1r double precision,
    s2r double precision,
    bi double precision,
    farmid integer,
    applratenclass text
) distribute by HASH(fileid);

CREATE TABLE nutrients.planningperiod (
    id integer NOT NULL,
    farmid integer,
    samplefieldid integer,
    fieldid integer,
    tstart timestamp without time zone,
    tend timestamp without time zone,
    state integer DEFAULT 0 NOT NULL,
    plannedsamplingdate timestamp without time zone,
    duration double precision DEFAULT 0 NOT NULL,
    calcstate integer DEFAULT 0 NOT NULL,
    calcerr integer DEFAULT 0 NOT NULL,
    appstat_p double precision[] DEFAULT ARRAY[0, 0, 0, 0, 0],
    appstat_k double precision[] DEFAULT ARRAY[0, 0, 0, 0, 0],
    appstat_mg double precision[] DEFAULT ARRAY[0, 0, 0, 0, 0],
    appstat_cao double precision[] DEFAULT ARRAY[0, 0, 0, 0, 0],
    sampstat_p double precision[] DEFAULT ARRAY[(-1), (-1), (-1)],
    sampstat_k double precision[] DEFAULT ARRAY[(-1), (-1), (-1)],
    sampstat_mg double precision[] DEFAULT ARRAY[(-1), (-1), (-1)],
    sampstat_ph double precision[] DEFAULT ARRAY[(-1), (-1), (-1)],
    firstyear integer,
    lastyear integer,
    calculationdate timestamp with time zone
) distribute by HASH(id);
